const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      oldPrice: 38,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi5.walmartimages.com%2Fasr%2Fb53e96bb-cd86-4815-b22a-4413b5d44145.6db569c8420c44e4057b3b4be0776042.jpeg&f=1&nofb=1&ipt=ef8fe14b87dbc1f5e08dc94c70ea38cb24b7509d46d66c3fb61fbb8528c6cca1&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: true,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.gentlemansgazette.com%2Fwp-content%2Fuploads%2F2015%2F10%2FA-completely-adjustable-ergonomic-chair.jpg&f=1&nofb=1&ipt=9a70c7dad3c09ca8f64932783c64c9b00eb590231807a58f6949796147db896c&ipo=images',
      favorite: false,
      comparision: true,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: true,
      comparision: true,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi5.walmartimages.com%2Fasr%2Fac75c7a0-07a0-405d-a748-58743d8ceb2d.7eb05d00f850a867b1f376b08d510e6e.jpeg&f=1&nofb=1&ipt=18c4396d71b14b34fab7987fbf6f0b5750c0c427b0f2c9899b3c0d3376367d36&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.y2uHbEzmnIA1Sj7wffCksAHaHa%26pid%3DApi&f=1&ipt=66a2d1481dcc586b788e29c0d0975888a6652183330206cda9f9e49f92f79e2d&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FI%2F71vcCmKRpeL._AC_SL1024_.jpg&f=1&nofb=1&ipt=954a9e13ace7a7ce07a4d061541a176f3b11b29e82e29d09871b153775c6c6f2&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimgdataserver.com%2Fitems%2Fhooker-ss-chaise-lounge-living-room-chair-hooss641cs097_zm.jpg&f=1&nofb=1&ipt=bd6b7cfe6eca7088561c9baa6d568d52ae99742567175e271f666f5718941ecd&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimgdataserver.com%2Fitems%2Fhooker-ss-chaise-lounge-living-room-chair-hooss641cs097_zm.jpg&f=1&nofb=1&ipt=bd6b7cfe6eca7088561c9baa6d568d52ae99742567175e271f666f5718941ecd&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimgdataserver.com%2Fitems%2Fhooker-ss-chaise-lounge-living-room-chair-hooss641cs097_zm.jpg&f=1&nofb=1&ipt=bd6b7cfe6eca7088561c9baa6d568d52ae99742567175e271f666f5718941ecd&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      oldPrice: 110,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fengineeringdiscoveries.com%2Fwp-content%2Fuploads%2F2021%2F04%2F6a7b51d92b1f3efedb994ee2620ddc56.jpg&f=1&nofb=1&ipt=ef7470c63a2514124c896467566df15b07403ef62bce7ef779659ccac7316a73&ipo=images',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      oldPrice: 0,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img:
        'https://duckduckgo.com/?q=chair&atb=v400-1&iax=images&ia=images&iai=https%3A%2F%2Fimgdataserver.com%2Fitems%2Fhooker-ss-chaise-lounge-living-room-chair-hooss641cs097_zm.jpg',
      favorite: false,
      comparision: false,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt alias modi veniam facere veritatis debitis iste dolorum accusantium molestias animi.',
    },
    {
      id: 'chair-1',
      name: 'Chair 1',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-2',
      name: 'Chair 2',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-3',
      name: 'Chair 3',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-4',
      name: 'Chair 4',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-5',
      name: 'Chair 5',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-6',
      name: 'Chair 6',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-7',
      name: 'Chair 7',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-8',
      name: 'Chair 8',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-9',
      name: 'Chair 9',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-10',
      name: 'Chair 10',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-11',
      name: 'Chair 11',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-12',
      name: 'Chair 12',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-13',
      name: 'Chair 13',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-14',
      name: 'Chair 14',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-15',
      name: 'Chair 15',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-16',
      name: 'Chair 16',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-17',
      name: 'Chair 17',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-18',
      name: 'Chair 18',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-19',
      name: 'Chair 19',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-20',
      name: 'Chair 20',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-21',
      name: 'Chair 21',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-22',
      name: 'Chair 22',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-23',
      name: 'Chair 23',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'chair-24',
      name: 'Chair 24',
      category: 'chair',
      price: 100,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/CLVD5Ykb/pexels-photo-7881483.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-1',
      name: 'Sofa 1',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-2',
      name: 'Sofa 2',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-3',
      name: 'Sofa 3',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-4',
      name: 'Sofa 4',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-5',
      name: 'Sofa 5',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-6',
      name: 'Sofa 6',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-7',
      name: 'Sofa 7',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-8',
      name: 'Sofa 8',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-9',
      name: 'Sofa 9',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-10',
      name: 'Sofa 10',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-11',
      name: 'Sofa 11',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-12',
      name: 'Sofa 12',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-13',
      name: 'Sofa 13',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-14',
      name: 'Sofa 14',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-15',
      name: 'Sofa 15',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-16',
      name: 'Sofa 16',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-17',
      name: 'Sofa 17',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-18',
      name: 'Sofa 18',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-19',
      name: 'Sofa 19',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-20',
      name: 'Sofa 20',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-21',
      name: 'Sofa 21',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-22',
      name: 'Sofa 22',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-23',
      name: 'Sofa 23',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'sofa-24',
      name: 'Sofa 24',
      category: 'sofa',
      price: 200,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/SsDRDFjt/pexels-andrea-piacquadio-3757055-3.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-1',
      name: 'Table 1',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-2',
      name: 'Table 2',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-3',
      name: 'Table 3',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-4',
      name: 'Table 4',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-5',
      name: 'Table 5',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-6',
      name: 'Table 6',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-7',
      name: 'Table 7',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-8',
      name: 'Table 8',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-9',
      name: 'Table 9',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-10',
      name: 'Table 10',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-11',
      name: 'Table 11',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-12',
      name: 'Table 12',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-13',
      name: 'Table 13',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-14',
      name: 'Table 14',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-15',
      name: 'Table 15',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-16',
      name: 'Table 16',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-17',
      name: 'Table 17',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-18',
      name: 'Table 18',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-19',
      name: 'Table 19',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-21',
      name: 'Table 21',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-22',
      name: 'Table 22',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-23',
      name: 'Table 23',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'table-24',
      name: 'Table 24',
      category: 'table',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sDhMpL9s/pexels-photo-276651.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-1',
      name: 'Dining 1',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-2',
      name: 'Dining 2',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-3',
      name: 'Dining 3',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-4',
      name: 'Dining 4',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-5',
      name: 'Dining 5',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-6',
      name: 'Dining 6',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-7',
      name: 'Dining 7',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-8',
      name: 'Dining 8',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-9',
      name: 'Dining 9',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-10',
      name: 'Dining 10',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-11',
      name: 'Dining 11',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-12',
      name: 'Dining 12',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-13',
      name: 'Dining 13',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-14',
      name: 'Dining 14',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-15',
      name: 'Dining 15',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-16',
      name: 'Dining 16',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-17',
      name: 'Dining 17',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-18',
      name: 'Dining 18',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-19',
      name: 'Dining 19',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-20',
      name: 'Dining 20',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-21',
      name: 'Dining 21',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-22',
      name: 'Dining 22',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-23',
      name: 'Dining 23',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
    {
      id: 'dining-24',
      name: 'Dining 24',
      category: 'dining',
      price: 250,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/QCMp8JRV/pexels-photo-534172.jpg',
      favorite: false,
      comparision: false,
    },
  ],
  cart: {
    products: [],
  },
};

export default initialState;
